"""Modificación de Material Topic

Revision ID: d04be2c59f42
Revises: fc396144d837
Create Date: 2025-04-29 16:28:27.877233+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd04be2c59f42'
down_revision: Union[str, None] = 'fc396144d837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('material_topics', 'priority',
               existing_type=mysql.ENUM('high', 'medium', 'low'),
               nullable=True)
    op.alter_column('material_topics', 'main_objective',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('material_topics', 'goal_ods_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('material_topics', 'goal_number',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('material_topics', 'goal_number',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('material_topics', 'goal_ods_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('material_topics', 'main_objective',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('material_topics', 'priority',
               existing_type=mysql.ENUM('high', 'medium', 'low'),
               nullable=False)
    # ### end Alembic commands ###
