"""Stakeholders.name no es unique

Revision ID: 70857c4cb060
Revises: 1c6a6c309fd0
Create Date: 2025-05-16 09:08:53.460484+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70857c4cb060'
down_revision: Union[str, None] = '1c6a6c309fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='stakeholders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'stakeholders', ['name'], unique=False)
    # ### end Alembic commands ###
