"""Diagnostic -> Diagnosis

Revision ID: e62311bc4899
Revises: efa33e5d8bca
Create Date: 2025-05-18 15:51:01.981679+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e62311bc4899'
down_revision: Union[str, None] = 'efa33e5d8bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('diagnosis_indicators',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.Text(), nullable=False),
    # sa.Column('type', sa.Enum('quantitative', 'qualitative', name='indicator_type'), nullable=False),
    # sa.Column('material_topic_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['material_topic_id'], ['material_topics.id'], onupdate='CASCADE', ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('diagnosis_indicators_qualitative',
    # sa.Column('diagnosis_indicator_id', sa.Integer(), nullable=False),
    # sa.Column('response', sa.Text(), nullable=False),
    # sa.ForeignKeyConstraint(['diagnosis_indicator_id'], ['diagnosis_indicators.id'], onupdate='CASCADE', ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('diagnosis_indicator_id')
    # )
    # op.create_table('diagnosis_indicators_quantitative',
    # sa.Column('diagnosis_indicator_id', sa.Integer(), nullable=False),
    # sa.Column('numeric_response', sa.DECIMAL(precision=10, scale=2), nullable=False),
    # sa.Column('unit', sa.String(length=100), nullable=False),
    # sa.ForeignKeyConstraint(['diagnosis_indicator_id'], ['diagnosis_indicators.id'], onupdate='CASCADE', ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('diagnosis_indicator_id')
    # )

    # Renombrar las tablas de diagnostic a diagnosis
    op.rename_table('diagnostic_indicators', 'diagnosis_indicators')
    op.rename_table('diagnostic_indicators_qualitative', 'diagnosis_indicators_qualitative')
    op.rename_table('diagnostic_indicators_quantitative', 'diagnosis_indicators_quantitative')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Restaurar los nombres originales de las tablas
    op.rename_table('diagnosis_indicators', 'diagnostic_indicators')
    op.rename_table('diagnosis_indicators_qualitative', 'diagnostic_indicators_qualitative')
    op.rename_table('diagnosis_indicators_quantitative', 'diagnostic_indicators_quantitative')

    # Eliminar las nuevas tablas
    op.drop_table('diagnosis_indicators_quantitative')
    op.drop_table('diagnosis_indicators_qualitative')
    op.drop_table('diagnosis_indicators')
    # ### end Alembic commands ###
