"""Modificación de Goal: el número de meta puede ser una letra

Revision ID: 0b2ba7baf93d
Revises: b988b501b95f
Create Date: 2025-04-29 17:17:28.594466+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b2ba7baf93d'
down_revision: Union[str, None] = 'b988b501b95f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Primero eliminamos la clave foránea
    op.drop_constraint('material_topics_ibfk_1', 'material_topics', type_='foreignkey')
    
    # Modificamos la columna en goals
    op.alter_column('goals', 'goal_number',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=2),
               existing_nullable=False)
    
    # Modificamos la columna en material_topics
    op.alter_column('material_topics', 'goal_number',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=2),
               existing_nullable=True)
    
    # Recreamos la clave foránea
    op.create_foreign_key(
        'material_topics_ibfk_1',
        'material_topics',
        'goals',
        ['goal_ods_id', 'goal_number'],
        ['ods_id', 'goal_number'],
        onupdate='CASCADE',
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Primero eliminamos la clave foránea
    op.drop_constraint('material_topics_ibfk_1', 'material_topics', type_='foreignkey')
    
    # Modificamos la columna en material_topics
    op.alter_column('material_topics', 'goal_number',
               existing_type=sa.String(length=2),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    
    # Modificamos la columna en goals
    op.alter_column('goals', 'goal_number',
               existing_type=sa.String(length=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    
    # Recreamos la clave foránea
    op.create_foreign_key(
        'material_topics_ibfk_1',
        'material_topics',
        'goals',
        ['goal_ods_id', 'goal_number'],
        ['ods_id', 'goal_number'],
        onupdate='CASCADE',
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###
