"""Internal_consistency_text

Revision ID: efa33e5d8bca
Revises: 25b4de62e857
Create Date: 2025-05-18 13:28:27.497723+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'efa33e5d8bca'
down_revision: Union[str, None] = '25b4de62e857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sustainability_reports', sa.Column('internal_consistency_description', sa.Text(), nullable=True))
    op.drop_column('sustainability_reports', 'internal_coherence_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sustainability_reports', sa.Column('internal_coherence_description', mysql.TEXT(), nullable=True))
    op.drop_column('sustainability_reports', 'internal_consistency_description')
    # ### end Alembic commands ###
