"""Nuevo atributo en Report: Survey State

Revision ID: 657496a30ed5
Revises: 0b2ba7baf93d
Create Date: 2025-04-30 09:30:57.801540+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '657496a30ed5'
down_revision: Union[str, None] = '0b2ba7baf93d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sustainability_reports', sa.Column('survey_state', sa.Enum('active', 'inactive', name='survey_state'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sustainability_reports', 'survey_state')
    # ### end Alembic commands ###
