"""Otro mas

Revision ID: 25b4de62e857
Revises: b58dbbcd6b1c
Create Date: 2025-05-16 18:02:58.451360+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b4de62e857'
down_revision: Union[str, None] = 'b58dbbcd6b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sustainability_reports', sa.Column('published_report', sa.Text(), nullable=True))
    op.add_column('sustainability_reports', sa.Column('action_plan_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sustainability_reports', 'action_plan_text')
    op.drop_column('sustainability_reports', 'published_report')
    # ### end Alembic commands ###
