"""ReportPhoto: description

Revision ID: 9ae5df08e447
Revises: 94f205138e8b
Create Date: 2025-05-01 16:17:48.081766+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae5df08e447'
down_revision: Union[str, None] = '94f205138e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_photos', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_photos', 'description')
    # ### end Alembic commands ###
