"""Renombrar algunos atributos y elimianr otros

Revision ID: b58dbbcd6b1c
Revises: 70857c4cb060
Create Date: 2025-05-16 13:26:25.289947+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b58dbbcd6b1c'
down_revision: Union[str, None] = '70857c4cb060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sustainability_reports', sa.Column('stakeholders_description', sa.Text(), nullable=True))
    op.drop_column('sustainability_reports', 'action_plan_text')
    op.drop_column('sustainability_reports', 'stakeholders_text')
    op.drop_column('sustainability_reports', 'internal_coherence_text')
    op.drop_column('sustainability_reports', 'action_plan_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sustainability_reports', sa.Column('action_plan_description', mysql.TEXT(), nullable=True))
    op.add_column('sustainability_reports', sa.Column('internal_coherence_text', mysql.TEXT(), nullable=True))
    op.add_column('sustainability_reports', sa.Column('stakeholders_text', mysql.TEXT(), nullable=True))
    op.add_column('sustainability_reports', sa.Column('action_plan_text', mysql.TEXT(), nullable=True))
    op.drop_column('sustainability_reports', 'stakeholders_description')
    # ### end Alembic commands ###
