"""El modelo del SustainabilityReport tiene más campos

Revision ID: fb67485b83a2
Revises: dc55fd6f614b
Create Date: 2025-05-16 06:29:14.306638+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fb67485b83a2'
down_revision: Union[str, None] = 'dc55fd6f614b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sustainability_reports', sa.Column('main_secondary_impacts_text', sa.Text(), nullable=True))
    op.drop_column('sustainability_reports', 'secondary_impacts_text')
    op.drop_column('sustainability_reports', 'main_impacts_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sustainability_reports', sa.Column('main_impacts_text', mysql.TEXT(), nullable=True))
    op.add_column('sustainability_reports', sa.Column('secondary_impacts_text', mysql.TEXT(), nullable=True))
    op.drop_column('sustainability_reports', 'main_secondary_impacts_text')
    # ### end Alembic commands ###
