"""El modelo del SustainabilityReport se ha quitado secondary impact y unificado y integrated text

Revision ID: 1c6a6c309fd0
Revises: ce62ccc67e80
Create Date: 2025-05-16 06:38:09.278159+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1c6a6c309fd0'
down_revision: Union[str, None] = 'ce62ccc67e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sustainability_reports', sa.Column('action_plan_text', sa.Text(), nullable=True))
    op.drop_column('sustainability_reports', 'context_temporal_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sustainability_reports', sa.Column('context_temporal_text', mysql.TEXT(), nullable=True))
    op.drop_column('sustainability_reports', 'action_plan_text')
    # ### end Alembic commands ###
