"""Tiempo de ejecución es de acción

Revision ID: 8e597e8d9c1b
Revises: 78f38465185c
Create Date: 2025-05-21 14:46:50.683640+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8e597e8d9c1b'
down_revision: Union[str, None] = '78f38465185c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('execution_time', sa.String(length=100), nullable=True))
    op.drop_column('specific_objectives', 'execution_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specific_objectives', sa.Column('execution_time', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('actions', 'execution_time')
    # ### end Alembic commands ###
