"""Action: ods_id Nullable

Revision ID: 968c4ed3b956
Revises: efd7aaddf700
Create Date: 2025-04-30 19:49:42.262937+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '968c4ed3b956'
down_revision: Union[str, None] = 'efd7aaddf700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actions', 'ods_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actions', 'ods_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
