"""El modelo del SustainabilityReport se ha quitado secondary impact y unificado y integrated text

Revision ID: ce62ccc67e80
Revises: fb67485b83a2
Create Date: 2025-05-16 06:32:45.789209+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ce62ccc67e80'
down_revision: Union[str, None] = 'fb67485b83a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sustainability_reports', 'integrated_introduction_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sustainability_reports', sa.Column('integrated_introduction_text', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
