"""El modelo del SustainabilityReport tiene más campos

Revision ID: dc55fd6f614b
Revises: 0373d5a32ae5
Create Date: 2025-05-16 06:04:41.666084+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc55fd6f614b'
down_revision: Union[str, None] = '0373d5a32ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sustainability_reports', sa.Column('stakeholders_text', sa.Text(), nullable=True))
    op.add_column('sustainability_reports', sa.Column('materiality_text', sa.Text(), nullable=True))
    op.add_column('sustainability_reports', sa.Column('main_impacts_text', sa.Text(), nullable=True))
    op.add_column('sustainability_reports', sa.Column('secondary_impacts_text', sa.Text(), nullable=True))
    op.add_column('sustainability_reports', sa.Column('materiality_matrix_text', sa.Text(), nullable=True))
    op.add_column('sustainability_reports', sa.Column('context_temporal_text', sa.Text(), nullable=True))
    op.add_column('sustainability_reports', sa.Column('internal_coherence_text', sa.Text(), nullable=True))
    op.add_column('sustainability_reports', sa.Column('integrated_introduction_text', sa.Text(), nullable=True))
    op.add_column('sustainability_reports', sa.Column('diffusion_text', sa.Text(), nullable=True))
    op.add_column('sustainability_reports', sa.Column('template', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sustainability_reports', 'template')
    op.drop_column('sustainability_reports', 'diffusion_text')
    op.drop_column('sustainability_reports', 'integrated_introduction_text')
    op.drop_column('sustainability_reports', 'internal_coherence_text')
    op.drop_column('sustainability_reports', 'context_temporal_text')
    op.drop_column('sustainability_reports', 'materiality_matrix_text')
    op.drop_column('sustainability_reports', 'secondary_impacts_text')
    op.drop_column('sustainability_reports', 'main_impacts_text')
    op.drop_column('sustainability_reports', 'materiality_text')
    op.drop_column('sustainability_reports', 'stakeholders_text')
    # ### end Alembic commands ###
