"""Pesos de impacto: valor por defecto 1.0

Revision ID: 94f205138e8b
Revises: 968c4ed3b956
Create Date: 2025-05-01 09:27:52.910568+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f205138e8b'
down_revision: Union[str, None] = '968c4ed3b956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
