"""Modificación de Material Topic: ID autoincremental

Revision ID: b988b501b95f
Revises: fe7817f56eb4
Create Date: 2025-04-29 16:54:44.609852+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b988b501b95f'
down_revision: Union[str, None] = 'fe7817f56eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
