"""Modificación de Material Topic: ID no autoincremental

Revision ID: fe7817f56eb4
Revises: d04be2c59f42
Create Date: 2025-04-29 16:52:52.358499+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe7817f56eb4'
down_revision: Union[str, None] = 'd04be2c59f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
