"""Atributos de seguridad

Revision ID: 78f38465185c
Revises: e62311bc4899
Create Date: 2025-05-19 13:55:22.802804+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '78f38465185c'
down_revision: Union[str, None] = 'e62311bc4899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diagnosis_indicators_qualitative', 'response',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.add_column('users', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_token_expiration', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('reset_token_state', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token_state')
    op.drop_column('users', 'reset_token_expiration')
    op.drop_column('users', 'reset_token')
    op.alter_column('diagnosis_indicators_qualitative', 'response',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
